language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
services:
  - redis-server
script:
 - dotnet restore
 - dotnet build
 - cd Gofer.NET.Tests && dotnet restore && dotnet test
 - cd .. && dotnet pack -c Release --version-suffix $(printf %05d $TRAVIS_BUILD_NUMBER)
 - dotnet nuget push ./bin/Release/Gofer.NET.*.nupkg -s https://www.myget.org/F/thor/api/v2/package -k $MYGET_KEY